# For more info on HTTP files go to https://aka.ms/vs/httpfile
@url = https://jsonplaceholder.typicode.com

GET {{url}}/todos/1
Content-Type: application/json
Accept: application/json


###
POST {{url}}/todos
Content-Type: application/json
Accept: application/json

{
  "title": "todo title" ,
  "completed": false
}




